# Generated by Django 4.2.2 on 2023-06-12 11:26

import autoslug.fields
import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=100, verbose_name='Category name'), slugify=categories.models.my_slugify, unique_with=['author__name', 'pub_date__month']),
        ),
    ]
