# Generated by Django 4.2.3 on 2023-07-04 11:22

import autoslug.fields
import categories.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=categories.models.my_slugify, unique_with=['name']),
        ),
    ]
